name: Sync plugin folder from dev to main

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  sync_plugin:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository with submodules
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true
          submodules_recursive: true

      - name: Checkout dev branch
        run: git checkout dev

      - name: Copy plugins from submodule
        run: |
          mkdir -p copied_auto_enum
          cp -r auto-enum/plugin/* copied_auto_enum/

          mkdir -p copied_auto_re
          cp auto_re/auto_re.py copied_auto_re/

      - name: Checkout main branch
        run: git checkout main

      - name: copy the plugins to main branch
        run: |
          if [ -f auto-enum/ida-plugin.json ]; then
            mv auto-enum/ida-plugin.json /tmp/ida-plugin.json
          fi
          rm -rf auto-enum/*
          cp -r copied_auto_enum/* auto-enum/
          rm -rf auto-enum/.gitignore
          if [ -f /tmp/ida-plugin.json ]; then
            mv /tmp/ida-plugin.json auto-enum/ida-plugin.json
          fi

          cp copied_auto_re/auto_re.py auto_re.py

      - name: Commit and push changes
        run: |
          git config --local user.email "email@example.com"
          git config --local user.name "GitHub Actions"
          git add auto_enum/ auto_re.py
          git commit -m "auto: Sync plugin from dev to main"
          git push origin main
